alias gc='git commit -m'
alias go='git checkout'
alias gb='git branch'
alias gh='git hist'
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias gp='git pull'
alias gl='git log --pretty=format:"%C(green)[%h]%C(reset) %s %C(bold red)%an%C(reset)%C(bold blue)%d%C(reset)" --graph --date=short'
